"""initial schema

Revision ID: 75ba087cc0b6
Revises:
Create Date: 2026-05-11 12:17:38.489925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75ba087cc0b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etfs',
    sa.Column('isin', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('issuer', sa.String(length=255), nullable=False),
    sa.Column('ter', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('replication_method', sa.String(length=50), nullable=True),
    sa.Column('distribution_policy', sa.String(length=20), nullable=True),
    sa.Column('domicile', sa.CHAR(length=2), nullable=True),
    sa.Column('aum_eur', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('inception_date', sa.Date(), nullable=True),
    sa.Column('index_tracked', sa.String(length=255), nullable=True),
    sa.Column('teilfreistellung_class', sa.String(length=20), nullable=True),
    sa.Column('last_ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('isin')
    )
    op.create_table('tax_constants',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('basiszins', sa.Numeric(precision=7, scale=6), nullable=False),
    sa.Column('sparerpauschbetrag_eur', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('teilfreistellung_equity', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('teilfreistellung_mixed', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('capital_gains_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('solidaritaetszuschlag_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('year')
    )
    op.create_table('comparisons',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('isin_a', sa.String(length=12), nullable=False),
    sa.Column('isin_b', sa.String(length=12), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['isin_a'], ['etfs.isin'], ),
    sa.ForeignKeyConstraint(['isin_b'], ['etfs.isin'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comparisons_isin_a'), 'comparisons', ['isin_a'], unique=False)
    op.create_index(op.f('ix_comparisons_isin_b'), 'comparisons', ['isin_b'], unique=False)
    op.create_index(op.f('ix_comparisons_ts'), 'comparisons', ['ts'], unique=False)
    op.create_table('prices',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('nav', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['isin'], ['etfs.isin'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isin', 'date', name='uq_prices_isin_date')
    )
    op.create_index(op.f('ix_prices_isin'), 'prices', ['isin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prices_isin'), table_name='prices')
    op.drop_table('prices')
    op.drop_index(op.f('ix_comparisons_ts'), table_name='comparisons')
    op.drop_index(op.f('ix_comparisons_isin_b'), table_name='comparisons')
    op.drop_index(op.f('ix_comparisons_isin_a'), table_name='comparisons')
    op.drop_table('comparisons')
    op.drop_table('tax_constants')
    op.drop_table('etfs')
    # ### end Alembic commands ###
